remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 

collections:
  articles:
    output: true

filters:
  slugify:
    type: python
    code: |
      import re
      import unicodedata

      def slugify(text):
          text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8')
          text = re.sub(r'[^\w\s]', '', text)
          text = re.sub(r'\s+', '-', text)
          return text.strip('-').lower()